spring:
  datasource:
    url: jdbc:h2:file:~/todo
    username: sa
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: embedded
      schema-locations: classpath:db/schema.sql
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl