spring:
  datasource:
    url: jdbc:h2:file:~/todo
    username: sa
    driver-class-name: org.h2.Driver
  sql:
    init:
      schema-locations: classpath:db/schema.sql

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl